name: CI Demo

# Event
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
# Jobs
jobs:
  build: #Job Name
    runs-on: ubuntu-latest # OS to run on
    # Actions
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo "Hello, world!"
      - name: Run a multi-line script
        run: |
          echo "Hello, world!"
          echo "This is a multi-line script."
      - name: List files
        run: ls ${{ github.workspace }}
      - name: Print github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Action completed
        run: echo "Action completed"
